### ISSUE TITLE
Create recruitment poster.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot#357]
https://drive.google.com/drive/u/0/#folders/0B_7IPKiQjuIZUUJlZHN6NWRGeDA

The crank arm fundraiser poster is a great place to start. (mainly, I like the logo).

**Comment by SeanKetring** [comment]
This is a modified version of the crankarm flyer

On Tue, May 12, 2015 at 9:10 PM, Ahmed Samara <notifications@github.com>
wrote:

> https://drive.google.com/drive/u/0/#folders/0B_7IPKiQjuIZUUJlZHN6NWRGeDA
>
> The crank arm fundraiser poster is a great place to start. (mainly, I like
> the logo).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IEEERobotics/bot2014/issues/357>.
>



-- 
Thank you, and have a good day!
Sean Ketring

Electrical Engineering Undergraduate

**Comment by SeanKetring** [comment]
Posted across campus
