### ISSUE TITLE
What needs to be ordered over the summer?

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot#359]
(This normally goes on the to-buy list, but I'm posting it here just to make sure everyone sees this so we can get it done ASAP)

* Robotic arm  
* Course materials (Best bet is to just buy them at Lowes when we go to build the course)  
* IMU  
* LIDAR (possibly unnecessary if we can just use the drone ones for now)   

Any other ideas?

**Comment by SeanKetring** [comment]
There is a BOM for course construction materials, and a beagle bone black because I don't know if we have a working bone left.

**Comment by kvijay1995** [comment]
I left a BeagleBone Black in the locker in a box (it's new) but it hasn't been configured.

**Comment by SeanKetring** [comment]
Thanks Vijay, I'll take a look for it

On Thu, Jun 4, 2015 at 12:14 AM, Vijay Thiagarajan <notifications@github.com
> wrote:

> I left a BeagleBone Black in the locker in a box (it's new) but it hasn't
> been configured.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IEEERobotics/bot2014/issues/359#issuecomment-108714003>
> .
>



-- 
Thank you, and have a good day!
Sean Ketring

Electrical Engineering Undergraduate
