### ISSUE TITLE
Reminder: Clean out the dead branches of code and make a new repository for 2015!

### ISSUE THREAD

**Issue by cdyoder** [IEEERobotics/bot#363]
Please and thank you (we have new members from comp sci and comp engineering who are very interested in our code base).

**Comment by AhmedSamara** [comment]
We're going to continue using the same repository, just tagged with a new version number release.

**Comment by dfarrell07** [comment]
You could change the repo name without much breakage.

**Comment by AhmedSamara** [comment]
I've changed the repo name to 'bot' unless anyone has a suggestion for a better name,

**Comment by dfarrell07** [comment]
+1 to bot (original name)

**Comment by SeanKetring** [comment]
We still need to clean the dead branches, there are so many that its tough to tell which ones are useful

**Comment by kvijay1995** [comment]
I could help closing the branches I started. If Ahmed does some of his we would be in pretty good shape.

**Comment by AhmedSamara** [comment]
Closed all defunct branches.
