### ISSUE TITLE
Testing Functionality of Skelebot

### ISSUE THREAD

**Issue by SeanKetring** [IEEERobotics/bot#371]
We need to test the new CS bot to make sure that it is able to be driven around and controlled.  Currently it has not been tested since its reconstruction.

**Comment by jonathonwpowell** [comment]
got bot to move with the app, but the NICs are crashing often during operation.

**Comment by SeanKetring** [comment]
Found an electrical problem the power board that were causing the NICs to crash.  Going to resolder a couple ground connections today, and see if this solves the problem

**Comment by SeanKetring** [comment]
Found a faulty connection that was cutting out power, outside of dark power, in a broken fuse holder on the switch board.  Replaced this and now the connection is secure.  I believe this will solve the issue with crashing.

**Comment by SeanKetring** [comment]
Skelebot is able to be driven and functional
