### ISSUE TITLE
Note: The repository name has changed from 'bot2014' to 'bot'

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot#373]
Just to save anyone the trouble of wondering why they can't pull.

You can fix your problems just by using:  

`git remote set-url origin git@github.com:IEEERobotics/bot.git`

**Comment by kvijay1995** [comment]
Do you think we should also update the Readme.md file to reflect the change in repo name? (It's a broken link if you click on the icon right now)

**Comment by dfarrell07** [comment]
> Do you think we should also update the Readme.md file to reflect the
change in repo name? (It's a broken link if you click on the icon right now)

Yes, please do so.

Generally, situations where you find broken docs for open source projects,
it's the right call to fix them. :)
