### ISSUE TITLE
Simplifying BeagleBone setup (not just dev environemtns) using Vagrant?

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot#375]
@dfarrell07 

Is there any reason to not do our configurations through a Vagrant machine, where the hardware-related files are just mounted to the VM, and just do all of our coding through that VM?

It seems to me like it would just be a really easy way to get new BeagleBones up and running quickly.

**Comment by dfarrell07** [comment]
I don't understand the proposal, sorry.

**Comment by dfarrell07** [comment]
I think the best way to both configure a bone and a Vagrant box for off-bone dev work is to create an Ansible role that does the proper config, then apply it to real bones or the Vagrant box (via the Vagrant Ansible provisioner) as-needed.

**Comment by dfarrell07** [comment]
That'll give you the same codepath for both installs and put all your config management in a single, very easy to work with, modern/awesome/good to learn tool.
