### ISSUE TITLE
Move out of Senior Design LAB ASAP

### ISSUE THREAD

**Issue by PaladinEng** [IEEERobotics/bot#382]
Gentlemen. I spoke to Bobby today, and we need to get the IEEE Stuff (Not robotics) out of the locker today. I know this is IEEE's responsibility, not ours. But it needs to come out. I suggest we bring it in to HKN

**Comment by AhmedSamara** [comment]
I've been in contact with the IEEE people for a while, and they've been
very slow to actually act on it.
(These things aren't even from the IEEE student branch).

I'll just tell them that the administrators want everything out ASAP and
hopefully they'll finally come and get it.


On Fri, Aug 28, 2015 at 10:26 AM, Alwyn Smith <notifications@github.com>
wrote:

> Gentlemen. I spoke to Bobby today, and we need to get the IEEE Stuff (Not
> robotics) out of the locker today. I know this is IEEE's responsibility,
> not ours. But it needs to come out. I suggest we bring it in to HKN
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IEEERobotics/bot/issues/382>.
>



-- 
Ahmed Samara
Computer Engineering

**Comment by SeanKetring** [comment]
Came and picked up stuff
