### ISSUE TITLE
Fork for bot 2015?

### ISSUE THREAD

**Issue by PaladinEng** [IEEERobotics/bot#388]
Now that we've "officially" started the competition season, should we fork the bot repo for the 2015 development?

Also, we probably need to plan on some teaching sessions for new people, once the winnowing has occurred. Github for certain, and I'd like to contribute code this year, so I need to learn how to use vagrant.

**Comment by dfarrell07** [comment]
I suggest just tagging and working from the same tree, not forking a new
repo.

**Comment by AhmedSamara** [comment]
Yeah, we're not going to be forking it, just adding a new tag and working from there.
