### ISSUE TITLE
Create omni-wheel driver.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot#399]
### Introduction   

2016 competition involves very precise manipulations, which may mean that something unreliable and unstable like mecanum wheels might be a bad move. Omni wheels solve a similair function.  #161 is the task for physically building it.
It's possible to use them the same way as Mecanum wheels using [Mecdriver](https://github.com/IEEERobotics/bot/blob/master/bot/driver/mec_driver.py), as experimented with in #179 , but ideally we'd use them the 'right' way, where it turned and drove when needed.

### Requirements   
* a hardware abstraction and interface where it can be issued commands such as rotate, strafe, etc. Deciding the appropriate interface is a part of the task, but one with the same level of abstraction as Mec_driver is expected.   

### Resources    
* [Use mecdriver as a model](https://github.com/IEEERobotics/bot/blob/master/bot/driver/mec_driver.py)
   * Mecdriver uses the same hardware (motor, cape, and signal wise), just a different frame and wheels.      
  * https://github.com/IEEERobotics/bot/wiki/Using-mec_driver      
* Talk to @ahmedsamara for help.

**Comment by AhmedSamara** [comment]
@khweerak

**Comment by dkaramitrov** [comment]
I am interested!

**Comment by JacobDremann** [comment]
Interested

**Comment by khweerak** [comment]
I am interested

**Comment by AhmedSamara** [comment]
@EthanAnd 
@HaydenLawrence 
@Djvacto

**Comment by imohame** [comment]
I'm going to set up the BB for this.

**Comment by LaurenBrennan** [comment]
I'll work on this too

**Comment by LaurenBrennan** [comment]
I am still interested but I wont be at the meeting tonight, could you guys update me when you finish tonight? Thanks!

**Comment by AhmedSamara** [comment]
@kvijay1995 Did this and it's working pretty well.
