### ISSUE TITLE
Getting a bone ready for the drivable bot

### ISSUE THREAD

**Issue by jasteve4** [IEEERobotics/bot#409]
We need some one to setup a bone with two nicks and install the code base. 

Also, test to make sure that the app can connected to the bot.

It's kind of important to be able to control the bot.

**Comment by kvijay1995** [comment]
The bone on the bot has been setup with the niks and the code base as of yesterday.

The motor's and server are yet to be tested.

**Comment by tabarrett** [comment]
I have tested the motors and servos for each wheel and taken current measurements, everything seems to be working and now Ahmed is going to test the computer-vision camera
