### ISSUE TITLE
Missing box of sensors.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot#413]
We have a tackle box full of various sensors (things like accelerometers, gyroscopes, etc) that is currently missing.

Most of the sensors look [something like this](http://www.trossenrobotics.com/resize/shared/images/PImages/S-SEN-09801.jpg?bw=1000&bh=1000) but with headers soldered in.

Let me know if you see it.

**Comment by cdyoder** [comment]
When you say a tackle box, do you mean an actual tackle box like someone would use if they were going fishing?

**Comment by jasteve4** [comment]
I gave it to Ahmed last night. It was in HKN.
