### ISSUE TITLE
Design competition robot. Critical Design Review 

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot#425]
Hey everyone, since it's nearly the end of the fall semester, I think it's time that we started discussing how we're going to assemble the final robot. We should at least have a design nailed down by the end of winter break, and we'll be having a meeting soon to discuss it, so please be prepared with ideas (and post them here).   
So far we have a few guidelines for how it needs to be assembled.

Keep in mind the requirements for the competition:    
*  cannot exceed 12” x 12” x 12” at the start of the match,
*  can expand to a maximum of 20” x 20” x 20” during the game.    
* Omni-wheels (unless someone has a good reason for not using them)    
* Must be able to mount Dagu arm       
* Lidar needs a field of vision. Some blind spots are acceptable, but keep them minimal.

@cdyoder and @jdekler  are currently working on a stable-chassis, would you guys mind discussing that as well?

(All senior members and anyone interested in building it should comment here just so we know to keep all of you involved)     

@SeanKetring 
@PaladinEng 
@ThomasMcLean 
@dmpage318 
@adwiii

**Comment by SeanKetring** [comment]
I have talked with alot of folks and I have an idea of what all of our ideas together includes I have some sketches of the final design of the bot:

![img_0591](https://cloud.githubusercontent.com/assets/7844136/11727813/2a5001d6-9f54-11e5-9b81-8bb47f8cbf84.jpg)
![img_0592](https://cloud.githubusercontent.com/assets/7844136/11727815/2a52e428-9f54-11e5-9e1b-7435f8cc53ec.jpg)
![img_0593](https://cloud.githubusercontent.com/assets/7844136/11727814/2a51b2e2-9f54-11e5-9b42-83563eb37587.jpg)

Picture quality is not great; sorry bout that.   We have to nail down what we are going to pursue as a final design this upcoming Tuesday, and then we need to build it over winter break.  We will be behind if we don't.

**Comment by adgooden** [comment]
Ahmed,

Can you remove me from the IEEE communications? Thanks

Andrew Gooden
North Carolina State University
Electrical and Computer Engineering
adgooden@ncsu.edu
