### ISSUE TITLE
Lower Chassis Review

### ISSUE THREAD

**Issue by jdekler** [IEEERobotics/bot#427]
Here are the current lower chassis designs. If everyone could review and suggest changes that need to be made that would be great. 

![chassisortho](https://cloud.githubusercontent.com/assets/8978212/11906699/93af115a-a59c-11e5-9816-1e1012b32853.JPG)
![chassistop](https://cloud.githubusercontent.com/assets/8978212/11906700/93af638a-a59c-11e5-98da-0a66123d70d3.JPG)
![chassisloortho](https://cloud.githubusercontent.com/assets/8978212/11906702/93b23cf4-a59c-11e5-834a-850f9b272237.JPG)
![nomotors](https://cloud.githubusercontent.com/assets/8978212/11906701/93b1394e-a59c-11e5-9a3b-083633726220.JPG)

**Comment by PaladinEng** [comment]
what are the sets of three large holes in the corners of the acrylic for?

**Comment by jdekler** [comment]
Wiring Holes. Mostly just for easier management. Now that Chris has posted the upper and lower bot it is apparent that the holes will move. I tried to place them close to where the vertical support beams would be so that it would be easy to run wire up and down.

**Comment by SeanKetring** [comment]
Acrylic was laser cut today, we are ready to start mounting motors. Do you have all the hardware you need to do this, or do we need to order some stuff @jdekler ?

**Comment by AhmedSamara** [comment]
https://drive.google.com/drive/u/0/folders/0B-T8lr4gzD9lU2NzeHYzbklDa3M

So we ran into some compatibility issues between solidworks and the software that my parents use for their laser cutter, so we had to do some conversions. Could anyone check to see if this looks right?   

Also @cdyoder @jdekler how important is it that all of the cut is aligned in the exact locations, assuming they're all still the same relative to each other?  

We can't align the edges like they do on any fancy laser cutters, so we're not going to use the acrylic sheets you gave me and just use bigger ones and cut a 12x12 square out of them. Is it too late to return the sheets we have?

**Comment by cdyoder** [comment]
The important piece is that all holes are alligned relative to each other.
If so, we can make it work, although it may not be easy/pretty.

Let's save the acrylic as I forsee us having other uses for it.

**Comment by AhmedSamara** [comment]
Is it normal for acrylic to catch on fire and melt?

**Comment by cdyoder** [comment]
Umm......no?

How badly damaged is the piece? Got a picture?

Sincerely,
Christopher D. Yoder
UGSA MAE Representative
North Carolina State University

**Comment by AhmedSamara** [comment]
Just kidding about the melting.
There was some fire and more melting than I expected, but only on the
removed bits, the board looks fine.
We do however have a small problem. At some point in the process of
converting between file types and putting them in a file together (so I
could cut them from the same sheet) one of them became smaller than the
other.
All of the holes are in the same place, but the edge and the mounting slant
thing got cut off.
Umm......no?

How badly damaged is the piece? Got a picture?

Sincerely,
Christopher D. Yoder
UGSA MAE Representative
North Carolina State University

On Wed, Dec 30, 2015 at 2:24 PM, Ahmed Samara <notifications@github.com>
wrote:

> Is it normal for acrylic to catch on fire and melt?
> On Dec 29, 2015 9:28 PM, "cdyoder" <notifications@github.com> wrote:
>
> > The important piece is that all holes are alligned relative to each
> other.
> > If so, we can make it work, although it may not be easy/pretty.
> >
> > Let's save the acrylic as I forsee us having other uses for it.
> > On Dec 29, 2015 9:07 PM, "Ahmed Samara" <notifications@github.com>
> wrote:
> >
> > >
> https://drive.google.com/drive/u/0/folders/0B-T8lr4gzD9lU2NzeHYzbklDa3M
> > >
> > > So we ran into some compatibility issues between solidworks and the
> > > software that my parents use for their laser cutter, so we had to do
> some
> > > conversions. Could anyone check to see if this looks right?
> > >
> > > Also @cdyoder <https://github.com/cdyoder> @jdekler
> > > <https://github.com/jdekler> how important is it that all of the cut
> is
> > > aligned in the exact locations, assuming they're all still the same
> > > relative to each other?
> > >
> > > We can't align the edges like they do on any fancy laser cutters, so
> > we're
> > > not going to use the acrylic sheets you gave me and just use bigger
> ones
> > > and cut a 12x12 square out of them. Is it too late to return the
sheets
> > we
> > > have?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/IEEERobotics/bot/issues/427#issuecomment-167917868
> >.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/IEEERobotics/bot/issues/427#issuecomment-167920591>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IEEERobotics/bot/issues/427#issuecomment-168059721>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/IEEERobotics/bot/issues/427#issuecomment-168060188>.

**Comment by cdyoder** [comment]
How much smaller?

Sincerely,
Christopher D. Yoder
UGSA MAE Representative
North Carolina State University

**Comment by AhmedSamara** [comment]
Is the picture not sending?

**Comment by cdyoder** [comment]
I do not see one either in my Gmail inbox or here on Github.

**Comment by AhmedSamara** [comment]
![img_20151230_150809](https://cloud.githubusercontent.com/assets/2405319/12058981/bf770b7a-af20-11e5-9e37-028fbcafcd23.jpg)

It's about an inch smaller, but at least one of them came out nicely.

I also went ahead and cut some vinyl outlines of this so we can manually drill holes on the sheets we already have if there are more issues, so we should be good.

**Comment by SeanKetring** [comment]
Lower chassis has been built to spec, and unless anyone objects, we can commit to using it in the competition bot.
