### ISSUE TITLE
Entire CAD model of the bot

### ISSUE THREAD

**Issue by cdyoder** [IEEERobotics/bot#428]
As a result of today's work, the entire bot (minus some stuff) is now on Github! The model in it's entirety can be found within the CAD repo. There is a read me text file (ASSEM_READ_ME.txt) which outlines the assembly files to open depending on the portion of the bot you wish to look at (for example, there is an assembly with the entire bot, the upper half, the lower half, etc.). The read me is not complete as of now but I will update it as we go throughout the next two weeks. 

One will note that there is work to be done on the upper half of the bot as all of the parts are not designed yet. That progress will be made as we go through the next two weeks. If anyone is able to 3D print, there are three files on the Google Drive (IEEE Ground Robotics -> 2015-2016 -> TO PRINT) which may be printed. 

Finally, as it stands right now, WE FIT WITHIN THE 12" X 12" X 12" BOX!  :D just fyi.... Below are two images of the model as it is saved. A design review is imminent and expected before the end of winter break. 

![iso](https://cloud.githubusercontent.com/assets/8527263/11908451/4fe1919c-a5aa-11e5-8f4e-91d0189ba372.PNG)
![sideview](https://cloud.githubusercontent.com/assets/8527263/11908456/563e7bf4-a5aa-11e5-9b88-561da7cb5cb1.PNG)

**Comment by PaladinEng** [comment]
How much clearance do we have between the robot and the "box" ?

**Comment by cdyoder** [comment]
The middle sheet of acrylic is almost 12"x12", so not much. Maybe 1/32"-3/32" on each side?

**Comment by PaladinEng** [comment]
Ok. How big is the tunnel?

**Comment by cdyoder** [comment]
The tunnel is 18"x18" in cross section I believe. Someone should  double
check though.
-Chris

**Comment by cdyoder** [comment]
Most recent version of the CAD model of the robot. The rough design of the upper half is complete and the parts are on order. Also, the dxf files are being generated by James as this issue is being posted. Pics are below:

![viewtat](https://cloud.githubusercontent.com/assets/8527263/11966606/cdbfbb16-a8ca-11e5-8e23-7e1fddbd3145.PNG)
![view2_12_22_15](https://cloud.githubusercontent.com/assets/8527263/11966613/d20f082a-a8ca-11e5-8d4d-8cac148a8c82.PNG)
![view3_12_22_15](https://cloud.githubusercontent.com/assets/8527263/11966612/d20ed508-a8ca-11e5-8423-e1ad50421354.PNG)
![view1_12_22_15](https://cloud.githubusercontent.com/assets/8527263/11966614/d20f6d9c-a8ca-11e5-974e-31c9d9673935.PNG)

**Comment by SeanKetring** [comment]
Model looks great!  Good job
