### ISSUE TITLE
Winter break meeting times.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot#429]
A lot of people are planning on working during the break.    
For the sake of preventing people from having to work alone, please check in here whenever you get to the lab, especially if you're someone that has lab access so that other people can know whether or not they'll have someone to work with when they come in.

**Comment by AhmedSamara** [comment]
Wednesday 12/23:

Ahmed Samara in @ 10:00

Vijay, Sean, and Will should be coming in later too.

**Comment by jasteve4** [comment]
Are you all done for the day? I am in the lab now.

Josh Stevens @ 2.22

**Comment by SeanKetring** [comment]
I'm here with Josh.  Will be here till 7pm or so

**Comment by SeanKetring** [comment]
Anyone else coming in today?

**Comment by AhmedSamara** [comment]
Ahmed in @ 11:00

The doors next to the oval are locked (even to card access), but the entrance next to the bus stop is unlocked.

**Comment by cdyoder** [comment]
Yoder in Troxler @ 0930.

I didn't try the doors by the oval but the doors nearest the bus stop are open. Also, if the deck is closed, does that mean free parking on campus within the deck?

**Comment by PaladinEng** [comment]
I parked yesterday on Oval Drive and did not get a ticket

**Comment by cdyoder** [comment]
Yoder, Samara, Ketring, Stevens in Troxler since ~1200 12/31/15

**Comment by SeanKetring** [comment]
Plan is to meet tomorrow at 12 in Troxler!

**Comment by cdyoder** [comment]
Yoder, 12:04pm, 1/5/16
