### ISSUE TITLE
Need to laser cut the hopper 

### ISSUE THREAD

**Issue by SeanKetring** [IEEERobotics/bot#436]
To continue making progress on the upper chassis we need to get the first revision hopper laser cut.  

@AhmedSamara can you get the following following files laser cut:

https://drive.google.com/file/d/0B-T8lr4gzD9lenVPQkExekJ5U3c/view?usp=sharing

https://drive.google.com/file/d/0B-T8lr4gzD9lVmxvUFpzT1l6Qzg/view?usp=sharing

**Comment by AhmedSamara** [comment]
Printed and dropped off in troxler.
