### ISSUE TITLE
Paint and prepare blocks.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot#462]
I just cut some new blocks (that are the actual correct size).

We need someone to paint them and glue QR codes on them.    

Details on the blocks are explained on page 6 of the rules:

https://docs.google.com/document/d/1ITIsL9fpTk5HKEJW1NENVrkgfCgXqONWpm0sevzeYmo/edit#

Paint is in the closet.

> Green - Lowe’s - “Rust-Oleum Stops Rust Quart Size Container Interior Gloss Hunter Green Oil-Base Paint”; Item #: 558151; Model #: 7738502
Red - Lowe’s - “Rust-Oleum Stops Rust Interior Gloss Sunrise Red Oil-Base Paint (Actual Net Contents: 32-fl oz)”; Item #:  558155; Model #: 7762502
Blue - Lowe’s “Rust-Oleum Stops Rust Quart Size Container Interior Gloss Royal Blue Oil-Base Paint”; item #: 558166; Model #: 7727502
Yellow - Lowe’s “Rust-Oleum Stops Rust Quart Size Container Interior Gloss Sunburst Yellow Oil-Base Paint”; Item #: 558162; Model #: 7747502

**Comment by SeanKetring** [comment]
Painted and prepared, good work
