### ISSUE TITLE
Meeting Times Over Spring Break 

### ISSUE THREAD

**Issue by SeanKetring** [IEEERobotics/bot#466]
Use this thread for coordinating meeting over spring break. 

Will be in the lab tomorrow by late morning ~ noon

To do:
-Replace IR-Cape PIC 
-Continue programming arm subroutines
-Reconfigure IR sensor mount

Could probably use a wiring diagram of the bot at some point, any new electrical devs want to handle that?  ~ @tabarrett 

@kvijay1995 @relnor  How's navigation going?  Did the wheels fall off?

**Comment by kvijay1995** [comment]
The wheels have been excellent. They haven't fallen off yet. Navigation development came to a standstill on Saturday since the IR-Cape caused I2C problems. Hoping to continue development tomorrow.

**Comment by mynameis7** [comment]
Will anyone be working later on in the break?

**Comment by PaladinEng** [comment]
I'll be in tomorrow at 6:30. I need to hear from James about the new
couplers

**Comment by SeanKetring** [comment]
I'll be in tomorrow as well, probably by 1pm or so

**Comment by kvijay1995** [comment]
@mynameis7 We probably will be working most of this week.

I'll be in today at around 2.30pm

**Comment by mynameis7** [comment]
Is anyone coming today? I will be on campus till about 4

**Comment by SeanKetring** [comment]
Will be there around 1:30

**Comment by SeanKetring** [comment]
Hackday is in full swing

**Comment by SeanKetring** [comment]
I can come in today After 3 if anyone wants to work together

**Comment by AhmedSamara** [comment]
Now that the robot has been merged into two parts, it's difficult for people to work on subsystems at the same time.

So we have a calendar for people to help schedule meeting times outside of the normal meetings.

We're only 2 weeks away from competition, and we're extremely close to being done. We need everyone to do what they can with this final push to make sure we can compete!

https://calendar.google.com/calendar/render?pli=1#main_7
