### ISSUE TITLE
Things to bring to SEcon 2016.

### ISSUE THREAD

**Issue by AhmedSamara** [IEEERobotics/bot#471]
If you think of anything we should bring, please list it here.  

Don't trust yourself to remember on the day of, if you think of anything at all, write it down.    

- JB weld (super important).     
- Backup couplers @jdekler   
- Backup cameras

**Comment by SeanKetring** [comment]
-The Robot
-The Course
-Battery and charger 
-Box of misc. tools 
-Backup PCBs (white box in locker) 
-Tackleboxes 
-PIC kit red debugger 
-Beagle bone power cable, mini usb cables 
-extra motor, bracket and coupler 
-Backup 3d printed parts
-Backup IR sensors
-Backup Omni wheels 
-Backup servos and servo horns 
-Wire and connectors 

-

**Comment by PaladinEng** [comment]
is there a backup partial robot?

**Comment by cdyoder** [comment]
Do we have an extra bone we can take? And extra acrylic in case the chassis cracks or needs a mod?
